FROM golang:1.17-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git

WORKDIR /go/go-opera
COPY . .

ARG GOPROXY
RUN go mod download
RUN make opera



FROM alpine:latest
RUN touch /var/run/supervisor.sock
RUN apk add --no-cache ca-certificates bash supervisor

COPY --from=builder /go/go-opera/build/opera /

EXPOSE 5050 18545 18546

ENTRYPOINT ["/opera"]
